name: Update PDF Links in Index

on:
  push:
    paths:
      - "Scores/**/*.pdf"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update PDF links in index.html
      run: |
        FILE="index.html"
        TMP_FILE="index.tmp.html"
        LIST_CONTENT="<ul id=\"chartsList\">"

        # Start the new list
        echo "$LIST_CONTENT" > "$TMP_FILE"

        # Find all PDF files in Scores recursively and create links
        find Scores -type f -name "*.pdf" | while read filepath; do
          filename=$(basename "$filepath")
          echo "  <li><a href=\"$filepath\">$filename</a></li>" >> "$TMP_FILE"
        done

        # Close the list
        echo "</ul>" >> "$TMP_FILE"

        # Replace the existing <ul id="chartsList"> with the new content
        sed -i "/<ul id=\"chartsList\">/,/<\/ul>/c\\$(cat $TMP_FILE)" "$FILE"

        # Remove temporary file
        rm "$TMP_FILE"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update index.html with PDF links from Scores"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
