name: Ensure PDF List Exists in Index

on:
  push:
    paths:
      - "Scores/**/*.pdf"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure chartsList exists & update it
      run: |
        FILE="index.html"
        TMP_FILE="index.tmp.html"
        LIST_CONTENT="<ul id=\"chartsList\">"

        # Start new list
        echo "$LIST_CONTENT" > "$TMP_FILE"

        # Generate links for all PDF files found in Scores/
        find Scores -type f -name "*.pdf" | while read filepath; do
          filename=$(basename "$filepath")
          echo "  <li><a href=\"$filepath\">$filename</a></li>" >> "$TMP_FILE"
        done

        echo "</ul>" >> "$TMP_FILE"

        # Check if chartsList already exists
        if grep -q '<ul id="chartsList">' "$FILE"; then
          # Replace existing chartsList
          sed -i "/<ul id=\"chartsList\">/,/<\/ul>/c\\$(cat $TMP_FILE)" "$FILE"
        else
          # Add new chartsList before </body> or at the end of the file
          sed -i "/<\/body>/i\\$(cat $TMP_FILE)" "$FILE"
        fi

        # Clean up temporary file
        rm "$TMP_FILE"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Ensure chartsList exists and update PDF links"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
