name: Update PDF Links in Index

on:
  push:
    paths:
      - "Scores/**/*.pdf"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update PDF list in index.html safely
      run: |
        FILE="index.html"
        TMP_FILE="index.tmp.html"
        NEW_LIST_FILE="new_list.html"
        LIST_CONTENT="<ul id=\"chartsList\">"

        # Start new list and store in a separate file
        echo "$LIST_CONTENT" > "$NEW_LIST_FILE"

        # Process PDFs line-by-line instead of a single large argument
        find Scores -type f -name "*.pdf" | while read filepath; do
          filename=$(basename "$filepath")
          echo "  <li><a href=\"$filepath\">$filename</a></li>" >> "$NEW_LIST_FILE"
        done

        echo "</ul>" >> "$NEW_LIST_FILE"

        # Check if <ul id="chartsList"> exists
        if grep -q '<ul id="chartsList">' "$FILE"; then
          # Use awk instead of sed to safely replace without argument size limits
          awk '
            BEGIN { in_list = 0 }
            /<ul id="chartsList">/ { in_list = 1; while (getline line < "'"$NEW_LIST_FILE"'") print line }
            /<\/ul>/ { in_list = 0; print }
            !in_list { print }
          ' "$FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$FILE"
        else
          # Append list before </body>
          sed -i "/<\/body>/i\\$(cat $NEW_LIST_FILE)" "$FILE"
        fi

        # Clean up
        rm "$NEW_LIST_FILE"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Fix: Safely update PDF list in index.html"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
